# Generated by Django 4.2.3 on 2026-04-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bill_id_alter_contract_id_alter_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='slip',
            field=models.ImageField(blank=True, null=True, upload_to='slips/'),
        ),
    ]
