# Generated by Django 4.2.3 on 2026-04-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bill_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('ว่าง', 'ว่าง'), ('ไม่ว่าง', 'ไม่ว่าง')], default='ว่าง', max_length=20),
        ),
    ]
