# Generated by Django 4.2.3 on 2026-04-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='slip',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='status',
        ),
        migrations.AddField(
            model_name='bill',
            name='electric',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='room_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='water',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
