# Generated by Django 4.2.3 on 2026-04-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_bill_slip_remove_bill_status_bill_electric_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='electric',
            new_name='electric_total',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='water',
            new_name='water_total',
        ),
        migrations.AddField(
            model_name='bill',
            name='electric_new',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='electric_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='electric_unit_price',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='bill',
            name='water_new',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='water_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='water_unit_price',
            field=models.FloatField(default=10),
        ),
    ]
