# Generated by Django 4.2.3 on 2026-04-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_electric_bill_electric_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='electric_new',
            field=models.IntegerField(default=0, verbose_name='เลขไฟใหม่'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='electric_old',
            field=models.IntegerField(default=0, verbose_name='เลขไฟเก่า'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='water_new',
            field=models.IntegerField(default=0, verbose_name='เลขน้ำใหม่'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='water_old',
            field=models.IntegerField(default=0, verbose_name='เลขน้ำเก่า'),
        ),
    ]
