# Generated by Django 4.2.3 on 2026-04-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_bill_electric_new_alter_bill_electric_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='slip',
            field=models.ImageField(blank=True, null=True, upload_to='slips/'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='electric_new',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='electric_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='water_new',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='water_old',
            field=models.IntegerField(default=0),
        ),
    ]
