# Generated by Django 4.2.3 on 2026-04-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bill_slip_alter_bill_electric_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='repairs/'),
        ),
    ]
