# Generated by Django 4.2.3 on 2026-04-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_maintenance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='repair/'),
        ),
    ]
