# Generated by Django 4.2.3 on 2026-04-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_maintenance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('รอดำเนินการ', 'รอดำเนินการ'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('เสร็จแล้ว', 'เสร็จแล้ว')], default='รอดำเนินการ', max_length=20),
        ),
    ]
